[global]
    server string = Laboratorio
    netbios name = host.lan
    workgroup = LABORATORIO
    interfaces = docker,20.20.20.1
    bind interfaces only = yes
    socket address = 172.30.0.4
    security = user
    guest account = nobody
    map to guest = Bad User
    server min protocol = NT1
    follow symlinks = yes
    wide links = yes
    unix extensions = no
    inherit owner = yes
    create mask = 0666
    directory mask = 02777
    force user = root
    force group = root
    force create mode = 0666
    force directory mode = 02777

    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

[Data]
    path = /tmp/smb
    comment = Shared Data
    writable = yes
    guest ok = yes
    guest only = yes
