name: Trivy Scan
on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        image:
          - mysql:8
          - guacamole/guacd
          - guacamole/guacamole
          - dockurr/windows
          - mailserver/docker-mailserver:latest
          - roundcube/roundcubemail:latest
          - dorowu/ubuntu-desktop-lxde-vnc:latest
    steps:
      - uses: actions/checkout@v5
      - name: Scan ${{ matrix.image }}
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          scan-ref: ${{ matrix.image }}
          format: table
          ignore-unfixed: true
          severity: CRITICAL
